### ISSUE TITLE
Allow for optional provision of a custom error message.

### ISSUE THREAD

**Issue by laurencegw** [konform-kt/konform#10]
It would be nice if every constraint function in the builder had an optional argument for providing your own custom messages. Literally just an extra `customMessage: String? = null` argument.

**Comment by timrobertsdev** [comment]
You can do this with the `hint` extension function on `Constraint`. An example is shown in the second code block [here](https://github.com/konform-kt/konform#advanced-use).

**Comment by laurencegw** [comment]
Already taken care of :D
