### ISSUE TITLE
Kotlin 2 & multiplatform support

### ISSUE THREAD

**Issue by jillesvangurp** [konform-kt/konform#102]
With the upcoming Kotlin 2 release (RC2 is out right now), we should update the build and make this a proper multiplatform project that supports all the targets. Since this project only relies on the standard lib, there's no good reason to not do this.

- [x] Use the improved DSL for multiplatform
- [x] Add Native, Wasm, and all the other platforms
- [x] Preserve language compatibility with older Kotlin versions

**Comment by dhoepelman** [comment]
Included in upcoming 0.6.0
