### ISSUE TITLE
Merge or close old pull requests and issues

### ISSUE THREAD

**Issue by jillesvangurp** [konform-kt/konform#103]
There are a few years of pull requests. Let's review and merge or close them.

**Comment by dhoepelman** [comment]
I was planning to eventually do this, but first want to get the release process fixed. Help to review/update/dismiss them would be greatly appreciated of course.

**Comment by dhoepelman** [comment]
I've closed/merged the open PRs. There's #65 which I know solves a real problem, haven't had time to look into if that's the best way to solve that yet.

Same needs to happen for the open issues

**Comment by jillesvangurp** [comment]
Great. I can chase up @NikkyAI; we work together

**Comment by dhoepelman** [comment]
Also went over all the issues
