### ISSUE TITLE
Remove ifPresent

### ISSUE THREAD

**Issue by raderio** [konform-kt/konform#11]
```
UserProfile::age ifPresent {
    minimum(0)
    maximum(150)
}
```
Why it is neccesary to have `ifPresent`? 
Just apply validation rules ony if value is not null in any case.

**Comment by cies** [comment]
In that case `minimum` and `maximum` (amoung others) need to work both on a nullable context and on a non-nullable context.

I think the `ifPresent` also makes the intent of the code more clear to the reader.

**Comment by nlochschmidt** [comment]
I agree with @cies.
