### ISSUE TITLE
Missing artifacts for the darwin targets. 

### ISSUE THREAD

**Issue by psuzn** [konform-kt/konform#118]
If I add the konform as a dependency on commonMain that also targets ios it doesn't find the artifact for it. 

![Screenshot 2024-07-01 at 15 55 38](https://github.com/konform-kt/konform/assets/19205305/e7392bd4-2c40-4dbb-99ac-57815bcad186)

It is likely because the current version of release ci runs on Linux and none of the Darwin artifacts (ios, macos, etc) have been published to the maven (though the codebase has support for them). 

From https://repo1.maven.org/maven2/io/konform/

![Screenshot 2024-07-01 at 16 12 31](https://github.com/konform-kt/konform/assets/19205305/70e1b81b-2559-496a-8f04-9b828796a2a9)

**Comment by dhoepelman** [comment]
That's correct, the workflows need to be set up to run under mac os. Will gladly accept a PR that changes it.

**Comment by dhoepelman** [comment]
Fixes by #119 , currently being released as 0.6.1

**Comment by psuzn** [comment]
Thanks @dhoepelman. 

Looks like the manual approval is only supported on Linux tho.

**Comment by dhoepelman** [comment]
That's a shame. I've manually resume the release process and see what I'll do with that one

**Comment by dhoepelman** [comment]
0.6.1 is on maven central and seems to have the right artifacts. Let me know if you have any more problems.
