### ISSUE TITLE
Missing artifact for iosSimulatorArm64 target

### ISSUE THREAD

**Issue by jedjaimesc** [konform-kt/konform#124]
If I add the konform as a dependency on commonMain that also targets iosSimulatorArm64 it doesn't find the artifact for it. Probably because it hasn't been to maven, though the code base should support it.
![Screenshot 2024-07-17 at 8 43 17 AM](https://github.com/user-attachments/assets/87f12ef3-8af8-47f2-94d5-588a71d8f2bd)

**Comment by dhoepelman** [comment]
It wasn't configured, see #125

**Comment by dhoepelman** [comment]
Releasing is blocked due to some changes sonatype (maven central) made, need to look into it

**Comment by dhoepelman** [comment]
0.6.2 with the fix is making it's way onto maven central as we speak
