### ISSUE TITLE
Opening ValidationBuilder

### ISSUE THREAD

**Issue by Humberd** [konform-kt/konform#157]
I would like to extend `ValidationBuilder` with my own extension functions on KProperty1.
Unfortunately, I cannot do it right now, becuase `ValidationBuilder` class is final.
Can we make this class open?

**Comment by dhoepelman** [comment]
Can you give an example of what you'd like to do?

**Comment by Humberd** [comment]
Currently I have this validator for a trimmed username value:

```kotlin
validate(RegisterRequest::username.name, { it.username.trim() }) {
    withinLength(3..50)
}
```

However, trimming values for validation would be a common case for me so I would like some shorthand functinos, for example:

```kotlin
RegisterRequest::username trimmed {
	withinLength(3..50)
}
```

Or maybe this way for some non-standard cases

```kotlin
RegisterRequest::username({it.username.trim()} {
    withinLength(3..50)
}
```

**Comment by dhoepelman** [comment]
Hmm, that's indeed not possible, need to think a little bit about the implications of opening the class up

You can however define your own extension functions on ValidationBuilder allowing this syntax:

```kotlin
validateTrimmed(RegisterRequest::username) {
  withinLength(3..50)
}

fun <T> ValidationBuilder<T>.validateTrimmed(prop: KProperty1<T, String>, init: ValidationBuilder<String>.() -> Unit) =
  validate(prop.name, { prop(it).trim() }, init)
```

In general, if a trimmed value is important for your data, I'd recommend adding it as a prop and both using and validating on that:
```kotlin
data class RegisterRequest(...) {
  val usernameTrimmed get() = username.trim()
}

RegisterRequest::usernameTrimmed {
  withinLength(3..50)
}
```

**Comment by dhoepelman** [comment]
@Humberd planning to release soon with 0.9.2, thanks for the suggestion!

**Comment by Humberd** [comment]
That's great! You rock 😀
