### ISSUE TITLE
`ifPresent` is redundant for non-nullable types

### ISSUE THREAD

**Issue by SerVB** [konform-kt/konform#166]
At the moment, `ifPresent` can be called for non-nullable properties, but it's then redundant and can be safely removed.

Could we make ifPresent compilable only for nullable types?

Or at least creating two versions of them, for nullable and non-nullable types, with the non-nullable version always throwing in runtime (and perhaps also returning Nothing, so that there is at least a compiler warning about unreachable code).

**Comment by dhoepelman** [comment]
The same holds true for `required`

It might work to add additional ifPresent/required functions that only work for non-null return types, would need to test. Overloads might be tricky
```kotlin
@Deprecated("ifPresent is superfluous for non-null results", ReplaceWith(""))
    public infix fun <R : Any> KProperty1<T, R>.ifPresent(init: ValidationBuilder<R>.() -> Unit): Unit = ifPresent(this, this, init)
```

>with the non-nullable version always throwing in runtime (and perhaps also returning Nothing, so that there is at least a compiler warning about unreachable code)

This is way too harsh, they can just remain working as they currently do with a deprecation warning. Blowing up excisting people's working-but-weird code is not a good idea.

Especially consider that something might have been nullable in the past, but then was changed to not-null and that was never noticed in the validation. This would cause an library upgrade to suddenly crash the code that was fine before.
