### ISSUE TITLE
Metadata errors when using in a multi-platform project commonMain

### ISSUE THREAD

**Issue by adamsar** [konform-kt/konform#22]
When including 0.2.0 in a multiplatform project, it is unusable in the commonMain source set due to some sort of metadata publishing error. 

I have an example repo set up to replicate this error here:
https://github.com/adamsar/kotlin-dependency-bug

**Comment by nlochschmidt** [comment]
Thanks for the report. Indeed it looks like the way multiplatform libraries need to be published has changed. I'll see what I can do on short notice.

**Comment by nlochschmidt** [comment]
Multiplatform is still in alpha state and looking at other libs like kotlinx.serialization, it seems to be a bit tricky to get the publishing right. 
I have published 0.3.0-RC1 to bintray and will have to cut a new release. Among other things, this also moves from Kotlin 1.3 to 1.4.

**Comment by adamsar** [comment]
Yeah, with mutliplatform in alpha, I decided to move away from it in any production/consumer facing project, so time is not particularly urgent on this. When it gets published I will definitely give it for a spin though.

For the record I am using this to bridge form/json validation from browser to server, and will probably make an adapter library for ktor or http4k.

**Comment by set321go** [comment]
i've been using `0.3.0-RC1` on my multiplatform project for a couple of weeks now no issues as far as i've noticed

**Comment by nlochschmidt** [comment]
After getting some help with switching from Bintray to MavenCentral, 0.3.0 has been released and should work as expected. Please let me know if you find issues with using konform in a multiplatform project.
