### ISSUE TITLE
Feature request: ability to validate string as a number.

### ISSUE THREAD

**Issue by davidmoshal** [konform-kt/konform#23]
Given: an HTTP request with a string parameter representing a number.
 (btw, this is all HTTP requests as all parameters are strings, or arrays of strings!)

Then: I'd like to be able to validate that this string represents a number, and validate that number.

For example, given a request which posts a user's age, eg: "56".  
I'd like to validate that the string is a number, and that it's a positive integer.

I imagine that this could be provided as `ifNumber`, in the same way as `isPresent`.

eg:
```kt
UserProfile::age ifNumber {
	minimum(0)
}
```

**Comment by nlochschmidt** [comment]
Hey, this is too specific to be included directly in konform.

However if it's a simple check for age and you are fine with allowing up to 199 you could do a regex based check

```kotlin
data class Person(val age: String)
val validation = Validation<Person> {
    Person::
        pattern("1{0,1}\\d{1,2}")
    }
}
```

Or you could also write a simple matcher:

```kotlin
fun ValidationBuilder<String>.inRange(range: IntRange): Constraint<String> {
    return addConstraint("number must be in range {0}", range.toString()) { 
        it.toIntOrNull() in range 
    }
}
```

and use it like this:
```kotlin
val validation = Validation<Person> {
    Person::age {
        inRange(0..199)
    }
}
```
