### ISSUE TITLE
hasSize not working as expected

### ISSUE THREAD

**Issue by 1gravity** [konform-kt/konform#24]
My expectation for `hasSize(100)` is that the property is exactly 100 characters long but the function is defined like this:
`hasSize(min: Int = Int.MIN_VALUE, max: Int = Int.MAX_VALUE)`
which translates to `hasSize(100, Int.MAX_VALUE)`.
I think there should be a one parameter function `hasSize(size: Int)` to prevent these misunderstandings and the two parameter function should not have default values for min/max.

**Comment by nlochschmidt** [comment]
Thank you for the feedback @1gravity, but could you check where `hasSize` is coming from? 
Because it's not part of konform 😅. Konform contains JSONSchema style validations `minItems` and `maxItems` instead.

**Comment by 1gravity** [comment]
Lol, sorry for that. Wrong validation library. I'll close this issue
