### ISSUE TITLE
Add 0.1.0 to MavenCentral

### ISSUE THREAD

**Issue by esbobkov** [konform-kt/konform#28]
Hello!

We have installed version 0.1.0 in legacy project and want to make a simple switch from Bintray to MavenCentral, but MavenCentral does not have version 0.1.0

Could You pulblish it?

**Comment by mreichelt** [comment]
Hi @esbobkov!

I couldn't find the 0.1.0 artifact anywhere online - but chances are you still have the JAR in your local maven cache. How about the idea to just copy that over to your project and include the JAR directly? :)

**Comment by esbobkov** [comment]
I have 0.1.0 jar locally. Can I send it to you?)

**Comment by nlochschmidt** [comment]
@esbobkov sorry for the inconvenience I caused for you. Publishing a lib to mavenCentral is not trivial and just having one jar is not helping, but if you have it you should be able to add it as a local dependency to your project. However I do wonder why you aren't able to upgrade to 0.3, which should be a drop-in replacement.

If I find some time I'll see whether I can republish version 0.1 and 0.2 on mavenCentral.

**Comment by esbobkov** [comment]
Ok. thanks!

I will try
