### ISSUE TITLE
Getting all errors for a result

### ISSUE THREAD

**Issue by oripwk** [konform-kt/konform#3]
Currently a `ValidationResult<T>` can be used to get errors for a specific field:
```kotlin
result[UserProfile::fullName]
```

Is there any way to get a map of all errors for a given validation (not a separate list for every field)?

**Comment by laurencegw** [comment]
This to me is the single biggest blocker to making this useable in a nice way.

I use various methods of validation, and I encapsulate them in my own interfaces. I think validation is a core part of your logic and should not be embedded in your peripheral http/server frameworks.

For the same reason, I would never expose the data classes or exceptions of an internally used framework in my own API. I will always translate them to my own data types.

Right now, if I wanted to translate the error messages raised by this framework into my own errors, I would have to do some nasty iteration involving reflection on my own classes and their fields.

Please expose the collection of all errors (`Map<List<String>, List<String>>`).

**Comment by jeminglin** [comment]
Seems I am not alone, ;)

**Comment by silversoul93** [comment]
#18

**Comment by nlochschmidt** [comment]
Version 0.2.0 now exposes the errors in the ValidationResult. 

The readme has been updated as well.
