### ISSUE TITLE
Allow putting hints on empty required block

### ISSUE THREAD

**Issue by cies** [konform-kt/konform#36]
From the README it is not clear how I put a hint on an empty required block.

```kotlin
    val validator = Validation<DealFormDto> {
      DealFormDto::closedBy required {}
    }
```

I get the "is required" default message when `closedBy` is not present. But how to set my own message?

This does not work:

```kotlin
    val validator = Validation<DealFormDto> {
      DealFormDto::closedBy required { hint "Closed by is missing" }
    }
```

**Comment by cies** [comment]
We now use this custom validation this in order to specify the `hint` on a required property:

```kotlin
fun <T : Any?> ValidationBuilder<T>.required() = addConstraint("is required") {
  if (it == null) {
    false
  } else {
    when (it) {
      is String -> it.isNotBlank()
      is Collection<*> -> it.isNotEmpty()
      else -> true
    }
  }
}
```

Which we use like this:

```kotlin
      FormDto::estimatedAnnualSales { required() hint "Estimated sales is required" } // Note we control the error message
      FormDto::estimatedAnnualSales ifPresent { minimum(0) hint "Estimated sales cannot be negative" }
```

Where before we'd do something like this:

```kotlin
      FormDto::estimatedAnnualSales required { minimum(0) hint "Estimated sales cannot be negative" }
      // Note we have no control over the error given when `estimatedAnnualSales` is omitted, it will always be "is required"
```

**Comment by cies** [comment]
And we now use this one as well:

```kotlin
/** Convenience method, same as `required()` but takes a name. */
fun <T : Any?> ValidationBuilder<T>.requiredAs(name: String) = addConstraint("{} is required", name) {
  if (it == null) {
    false
  } else {
    when (it) {
      is String -> it.isNotBlank()
      is Collection<*> -> it.isNotEmpty()
      else -> true
    }
  }
}
```

**Comment by nlochschmidt** [comment]
Awesome that you found a solution that works using the existing extension points 👏 

> Which we use like this:
> ```
>     FormDto::estimatedAnnualSales { required() hint "Estimated sales is required" } // Note we control the error message
>     FormDto::estimatedAnnualSales ifPresent { minimum(0) hint "Estimated sales cannot be negative" }
> ```

I agree, that doesn't look very good to me

So additionally to the one design option you proposed there are at least two other design options that I think are interesting:

Option 1: Your proposed option

```kotlin
DealFormDto::closedBy required { hint "Closed by is missing" }
```

Option 2: Using optional `hint` parameter on `required`

```kotlin
DealFormDto::closedBy required(hint = "Closed by is missing") { }
```

Option 3: Using infix after the required block

```kotlin
DealFormDto::closedBy required { } hint "Closed by is missing"
```

Without having tried this, I believe Option 3 is most in line with the existing idioms and might possibly be also easier to implement.

**Comment by dhoepelman** [comment]
Option 3 makes sense. Currently many things return `Unit`, and they could be returning something along the lines of Constraint to which hints can be added. Alternatively, they return ValidationResultBuilder and there's a way to add hints to those. This might also be a way to solve #76

**Comment by dhoepelman** [comment]
API for this introduced in https://github.com/konform-kt/konform/pull/172
