### ISSUE TITLE
Add Kotlin/Wasm support

### ISSUE THREAD

**Issue by sdeleuze** [konform-kt/konform#68]
I would be interested to get Kotlin/Wasm support for https://github.com/sdeleuze/kowasm/, see more context in [this blog post](https://seb.deleuze.fr/the-huge-potential-of-kotlin-wasm/).

Currently blocked by https://youtrack.jetbrains.com/issue/KT-57276.

**Comment by nlochschmidt** [comment]
Oh interesting. Thanks for the heads-up.

**Comment by dhoepelman** [comment]
Same issue as here:
https://github.com/konform-kt/konform/pull/58#issuecomment-2027197447

Before investing in this there needs to interested, preferably also by someone willing to contribute the support

**Comment by dhoepelman** [comment]
A full multiplatform build will be in the next release, change in https://github.com/konform-kt/konform/pull/106
