### ISSUE TITLE
Add support for other regex matching functions

### ISSUE THREAD

**Issue by Giuliopime** [konform-kt/konform#71]
Konform uses `.match()` internally for the `pattern` validation.

It would be nice if there was an option to choose which method would be used in the regex validation, for example being able to choose `containsMatchIn()` or `find()` instead of `match()`.
This would make some specific usages of `pattern` a bit more efficient and easier to work with.

**Comment by dhoepelman** [comment]
Fixed by #165 , which introduces `containsPattern`
