### ISSUE TITLE
Recursive validation support

### ISSUE THREAD

**Issue by jishindev** [konform-kt/konform#74]
_Did not find anything related in the issues tab, so creating one to understand whats possible._ 

I have a set of data classes where one class references itself as a List. I'm unable to find a way to write a validator that can support this. Please share your thoughts on what can be done here.

Sample data classes - 
```
data class Section(val components: List<Component>) {
    data class Component(val subComponents: List<Component>)
}
```

**Comment by jishindev** [comment]
Resurfacing. Would appreciate any sort of inputs, possible timelines or workarounds to solve for the above case.

**Comment by dhoepelman** [comment]
did you try a lazy initializer and function ref to solve the self-reference? Not 100% sure you need the lazy, just the function might be enogh.

```kotlin
val validateComponent: Validation<Component> by lazy {
    Component::subComponents onEach {
      run(validateComponentRef())
    }
}
private fun validateComponentRef(): Validation<Component> =  validateComponent
```
