### ISSUE TITLE
Project abandoned?

### ISSUE THREAD

**Issue by Nek-12** [konform-kt/konform#79]
Threre haven't been any updates for a year now. Issues are unresolved and untriaged
Should we migrate from this library?

**Comment by dhoepelman** [comment]
My org might be interested in forking or providing a maintainer

**Comment by Nek-12** [comment]
Me too, I would contribute if someone would accept a PR

**Comment by mengio001** [comment]
I'm looking for a tool similar to .NET FluentValidation to check data class libraries. I'm also ready to help with this project by doing testing and helping with the coding. Let me know if there's more to do with this project and how I can assist.

**Comment by dhoepelman** [comment]
I've contacted the maintainer through email to request maintership, if I don't get a reply in a reasonable timeframe or a negative reply I'll create an amicable fork.

**Comment by dhoepelman** [comment]
@nlochschmidt has given me maintainer rights and we've now entered a transfer period where I will fully take over at some point. He will make the announcement, including where to report if you are interested in contributing:

https://github.com/konform-kt/konform/discussions/38
https://github.com/konform-kt/konform/issues/32
