### ISSUE TITLE
Add support for conditional/dependent validation

### ISSUE THREAD

**Issue by raderio** [konform-kt/konform#8]
For example I want to validate an email field, I want to validate it against a regexp pattern, and only it is a valid email I want to check if it is already taken(persisted in database).

**Comment by nlochschmidt** [comment]
Good idea. I would be open for a pull request for this.

I am not quite sure yet how the DSL should look like. One possibility I could think of would look like this

```
Person::email {
    inOrder {
        pattern("\\w+@bigcorp.com") hint "Organizers must have a BigCorp email address"
        uniqueInDatabase(dao) hint "Email has been taken"
    }
}
```

**Comment by dhoepelman** [comment]
I would not recommend anyone doing this and keep things like network calls and database lookups separate from the unitial validation, but it would be possible by adding free-form validations, which #65 does
